---
- hosts: all
  tasks:
  - name: create a temporary file for additional data
    file: 
        path: /tmp/tmp-{{Id}}
        state: touch
    become: true

  - name: prepare additional data
    shell: echo {{additionalData}} > /tmp/tmp-{{Id}}
    become: true

  - name: execute upgrade software operation
    shell: ./swm/upgrade-software.sh {{pnfId}} {{oldSwVersion}} {{targetSwVersion}} /tmp/tmp-{{Id}}

  - name: remove the temporary file
    file:
        path: /tmp/tmp-{{Id}}
        state: absent
    become: true
