version: '3'

services:
  mariadb:
    image: nexus3.onap.org:10001/mariadb:10.1.11
    ports:
      - "3306:3306"
    container_name: mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../archives/csit-dbinit.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    hostname:
      mariadb
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  aaisim:
    image: rodolpheche/wiremock
    ports:
      - "8080:8080"
    command: --verbose
    container_name: aaisim
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./aaisimulator/wiremock:/home/wiremock:ro
    hostname:
      aaisim
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  sdnc:
    image: onap/sdnc-image:latest
    container_name: sdnc_controller
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $SDNC_CERT_PATH:/opt/opendaylight/current/certs
      - ./aaisimulator/aaiclient.properties:/opt/onap/sdnc/data/properties/aaiclient.properties:ro
    entrypoint: ["/opt/onap/sdnc/bin/startODL.sh"]
    ports:
      - "8282:8181"
    hostname:
      sdnc
    links:
      - mariadb:dbhost
      - mariadb:sdnctldb01
      - mariadb:sdnctldb02
      - aaisim:aaihost
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
      - SDNC_BIN=/opt/onap/sdnc/bin
      - ODL_CERT_DIR=/tmp
      - ODL_ADMIN_USERNAME=${ODL_USER}
      - ODL_ADMIN_PASSWORD=${ODL_PASSWORD}
      - ODL_USER=${ODL_USER}
      - ODL_PASSWORD=${ODL_PASSWORD}
      - ODL_CERT_DIR=/opt/opendaylight/current/certs
      - SDNC_DB_INIT=true
      - HONEYCOMB_USER=${HONEYCOMB_USER}
      - HONEYCOMB_PASSWORD=${HONEYCOMB_PASSWORD}
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - SO_USER=${SO_USER}
      - SO_PASSWORD=${SO_PASSWORD}
      - NENG_USER=${NENG_USER}
      - NENG_PASSWORD=${NENG_PASSWORD}
      - CDS_USER=${CDS_USER}
      - CDS_PASSWORD=${CDS_PASSWORD}
      - ANSIBLE_USER=${ANSIBLE_USER}
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
      - SQL_CRYPTKEY=${SQL_CRYPTKEY}
      - A1_TRUSTSTORE_PASSWORD=a1adapter
      - KARAF_CONSOLE_LOG_LEVEL=info
    depends_on:
      - mariadb
    dns:
      - ${DNS_IP_ADDR-10.0.100.1}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
