version: "2.2"
services:
  sdnrdb:
    image: ${ES_IMAGE}:${ES_VERSION}
    container_name: sdnrdb
    environment:
      - discovery.type=single-node
    networks:
      integration:
        ipv4_address: ${ESDB_IP}
  sdnr:
    environment:
      - SDNRDBURL=http://sdnrdb:9200
networks:
  integration:
    name: ${NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${NETWORK_SUBNET}
        gateway: ${GATEWAY_IP}
