version: '2'
#networks:
        # integration:
        #    external: true
services:
   honeycomb:
      container_name: "11"
      image: gn:latest
      ports:
        - "2850:2831"
      hostname: honeycomb
      command: honeycomb
      volumes:
        - ./config:/opt/app/honeycomb/config
      environment:
        - enodebsimIp=10.31.4.14
        - enodebsimPort=2850
      restart: on-failure
      #      networks:
      #  - integration
