---
- hosts: all
  tasks:
  - name: create a temporary file for additional data
    file: 
        path: /tmp/tmp-{{Id}}
        state: touch
    become: false

  - name: prepare additional data
    shell: echo {{additionalData}} > /tmp/tmp-{{Id}}
    become: false

  - name: execute pre-check operation
    shell: ./swm/upgrade-pre-check {{pnfId}} {{oldSwVersion}} {{targetSwVersion}} {{ruleName}} /tmp/tmp-{{Id}}
    ignore_errors: yes
    register: precheck_result

  - name: write output to file
    local_action: shell echo -n "{{precheck_result.stdout}}" > "/{{inventory_dir}}/{{inventory_hostname}}_results.txt"
    when: precheck_result.stdout != ""

  - name: remove the temporary file
    file:
        path: /tmp/tmp-{{Id}}
        state: absent
    become: false

  - name: use result of pre-check as the result of Playbook
    fail:
      msg: "{{precheck_result.stderr}}"
    when: precheck_result is failed

