---
- hosts: all
  tasks:

  - name: parameter neIdentifier
    set_fact:
      ne_identifier: "{{neIdentifier}}"
    when: neIdentifier is defined

  - name: compatible with parameter pnfName
    set_fact:
      ne_identifier: "{{pnfName}}"
    when: neIdentifier is not defined and pnfName is defined

  - name: create a temporary file for additional data
    tempfile: 
      state: file
    register: additional_data_file

  - name: prepare additional data
    copy:
      content: "{{additionalData}}"
      dest: "{{additional_data_file.path}}"

  - name: execute post-check operation
    shell: ./swm/upgrade-post-check {{ne_identifier}} {{oldSwVersion}} {{targetSwVersion}} {{ruleName}} {{additional_data_file.path}}
    ignore_errors: yes
    register: postcheck_result

  - name: write output to file
    local_action: copy content="{{postcheck_result.stdout}}" dest="{{inventory_dir}}/{{inventory_hostname}}_results.txt"
    when: postcheck_result.stdout != ""

  - name: remove the temporary file
    file:
      path: "{{additional_data_file.path}}"
      state: absent
    when: additional_data_file.path is defined

  - name: build error message
    set_fact:
      err_msg:
        "reason": "{{postcheck_result.stderr}}"
        "result": "Failure"
    when: postcheck_result is failed and postcheck_result.stdout == "" and postcheck_result.stderr != ""

  - name: write error message to file
    local_action: copy content="{{err_msg}}" dest="{{inventory_dir}}/{{inventory_hostname}}_results.txt"
    when: postcheck_result is failed and postcheck_result.stdout == "" and postcheck_result.stderr != ""

  - name: use result of post-check as the result of Playbook
    fail:
      msg: "{{postcheck_result.stderr}}"
    when: postcheck_result is failed

