version: '2.1'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU}


services:

  db:
    image: mariadb:10.5
    container_name: sdnc_db_container
    ports:
      - "23306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  ansible:
    image: onap/sdnc-ansible-server-image:latest
    depends_on :
      - db
    container_name: sdnc_ansible_container
    entrypoint: ["/opt/ansible-server/startAnsibleServer.sh"]
    ports:
      - "8000"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ANSIBLE_TRUSTSTORE_PASSWORD=${ANSIBLE_TRUSTSTORE_PASSWORD}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  sdnc:
    image: onap/sdnc-image:latest
    depends_on :
      - db
      - ansible
    container_name: sdnc_controller
    entrypoint: ["/opt/onap/sdnc/bin/startODL.sh"]
    ports:
      - "8282:8181"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - ansible:ansiblehost
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
      - SDNC_BIN=/opt/onap/sdnc/bin
      - ODL_CERT_DIR=/tmp
      - ODL_ADMIN_USERNAME=${ODL_USER}
      - ODL_ADMIN_PASSWORD=${ODL_PASSWORD}
      - ODL_USER=${ODL_USER}
      - ODL_PASSWORD=${ODL_PASSWORD}
      - SDNC_DB_INIT=true
      - HONEYCOMB_USER=${HONEYCOMB_USER}
      - HONEYCOMB_PASSWORD=${HONEYCOMB_PASSWORD}
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - SO_USER=${SO_USER}
      - SO_PASSWORD=${SO_PASSWORD}
      - NENG_USER=${NENG_USER}
      - NENG_PASSWORD=${NENG_PASSWORD}
      - CDS_USER=${CDS_USER}
      - CDS_PASSWORD=${CDS_PASSWORD}
      - ANSIBLE_USER=${ANSIBLE_USER}
      - ANSIBLE_PASSWORD=${ANSIBLE_PASSWORD}
      - SQL_CRYPTKEY=${SQL_CRYPTKEY}
      - A1_TRUSTSTORE_PASSWORD=a1adapter
    # The default truststore for A1 adapter can be overridden by mounting a new
    # truststore (uncomment the lines below), whereas the corresponding password
    # should be updated in A1_TRUSTSTORE_PASSWORD environment variable (in the line above)
    #volumes:
    #  - ./a1_truststore.jks:/opt/onap/sdnc/data/stores/truststore.a1.adapter.jks:ro
    dns:
      - ${DNS_IP_ADDR-10.0.100.1}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
    extra_hosts:
        aaf.osaaf.org: 10.12.6.214

  dgbuilder:
    image: onap/ccsdk-dgbuilder-image:latest
    depends_on:
      - db
    container_name: sdnc_dgbuilder_container
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/onap/ccsdk/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3000:3100"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SDNC_CONFIG_DIR=/opt/onap/ccsdk/data/properties
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  ueblistener:
    image: onap/sdnc-ueb-listener-image:latest
    depends_on:
      - db
    container_name: sdnc_ueblistener_container
    entrypoint: ["/opt/onap/sdnc/ueb-listener/bin/start-ueb-listener.sh" ]
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
      - PROPERTY_DIR=/opt/onap/sdnc/data/properties
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ODL_USER=${ODL_USER}
      - ODL_PASSWORD=${ODL_PASSWORD}
      - ASDC_USER=${ASDC_USER}
      - ASDC_PASSWORD=${ASDC_PASSWORD}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"

  dmaaplistener:
    image: onap/sdnc-dmaap-listener-image:latest
    depends_on:
      - db
    container_name: sdnc_dmaaplistener_container
    entrypoint: ["/opt/onap/sdnc/dmaap-listener/bin/start-dmaap-listener.sh" ]
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - SDNC_CONFIG_DIR=/opt/onap/sdnc/data/properties
      - PROPERTY_DIR=/opt/onap/sdnc/data/properties
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - ODL_USER=${ODL_USER}
      - ODL_PASSWORD=${ODL_PASSWORD}
      - DMAAP_USER=${DMAAP_USER}
      - DMAAP_PASSWORD=${DMAAP_PASSWORD}
      - DMAAP_AUTHKEY=${DMAAP_AUTHKEY}
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"
