version: '2'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU}


services:
  db:
    image: mysql/mysql-server:5.6
    container_name: sdnc_db_container
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - MYSQL_ROOT_HOST=%
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"


  sdnc:
    image: openecomp/sdnc-image:latest
    depends_on :
      - db
    container_name: sdnc_controller_container
    entrypoint: ["/opt/openecomp/sdnc/bin/startODL.sh"]
    ports:
      - "8282:8181"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/openecomp/sdnc/data/properties
    dns:
      - 10.0.100.1
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"


  web:
    image: openecomp/admportal-sdnc-image:latest
    depends_on:
      - db
    container_name: sdnc_portal_container
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/openecomp/sdnc/admportal/shell && ./start_portal.sh"
    ports:
      - "8843:8843"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/openecomp/sdnc/data/properties
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"


  dgbuilder:
    image: openecomp/dgbuilder-sdnc-image:latest
    depends_on:
      - db
    container_name:  sdnc_dgbuilder_container
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/openecomp/sdnc/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3000:3100"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - sdnc:sdnhost
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/openecomp/sdnc/data/properties
    logging:
      driver:   "json-file"
      options:
        max-size: "30m"
        max-file: "5"


