# Base ubuntu with added packages needed for open ecomp
FROM onap/ccsdk-ubuntu-image:${project.version}
MAINTAINER SDNC Team (onap-sdnc@lists.onap.org)
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV SDNC_CONFIG_DIR /opt/onap/sdnc/data/properties


# copy deliverables to opt
COPY opt /opt


